version: "3"

services:
  ostree-puller:
    image: foundries/ostree-puller
    environment:
      FACTORY: $FACTORY
      TOKEN: $TOKEN
      OSTREE_REPO_ROOT: /repo
    volumes:
     - $REPO_ROOT:/repo
     - $PWD:/work
    command: /work/pull $OSTREE_HASH $OSTREE_REPO_ROOT
    extra_hosts:
      - "ostree.foundries.io:34.72.155.201"
      - "ota-lite.foundries.io:35.226.199.159"
      - "api.foundries.io:34.66.221.89"
